### ISSUE TITLE
How do updates to a metadata standard affect the search index?

### ISSUE THREAD

**Issue by mark-saeon** [SAEONData/ckanext-metadata#45]
The metadata_standard_index_create action uses the 'name' attribute of the standard for the name of the index, and 'metadata_template_json' to initialize the index. Furthermore, the metadata_record_index_update action, which is automatically triggered by applicable changes to metadata records or their workflow states, uses the associated metadata standard's 'name' to specify which index to update.

Now, what happens if an admin user modifies either 'name' or 'metadata_template_json'? Here are a few things to consider:
- Do we prevent such changes if an index already exists? This would imply that we must store on the metadata standard the fact that a corresponding search index has been created.
- Do we automatically create a new index and trash the old one and reindex all the metadata?
- How is the search UI going to reference a particular index? Will we store the index name in its configuration?
- Versioning of a standard is catered for on the metadata standard object itself - which has 'standard_name' and 'standard_version' attributes, so a change to 'metadata_template_json' would usually be a correction rather than a new version of a standard - in the latter case, we'd want a new metadata_standard object to be created instead. Although, a change to 'metadata_template_json' could (possibly, though unlikely) also be made because of a minor update to the real-life standard that the object represents - or to SAEON's flavour of it.
- Note that the 'name' field is (currently) automatically generated from 'standard_name' and 'standard_version', and will be regenerated on update too if either of those fields is modified.

**Comment by marksparkza** [comment]
Obsolete - Elasticsearch index management is no longer the responsibility of the metadata management system.
